name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Deploy Services
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USERNAME}}
        run: |
          SERVICES=(ChatService ClassroomService RolesService SubjectService UserService VideoService)
          PORTS=(3001 4001 5001 6001 7001 8001)

          for i in "${!SERVICES[@]}"; do
            SERVICE="${SERVICES[$i]}"
            LOWERCASE_SERVICE="$(echo "$SERVICE" | tr '[:upper:]' '[:lower:]')"  # Convert service name to lowercase
            
            cd ./$SERVICE
            docker build -t rahul4884/$LOWERCASE_SERVICE:latest .  # Use lowercase service name for tagging
            docker push rahul4884/$LOWERCASE_SERVICE:latest  # Push image with lowercase service name
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "docker pull rahul4884/$LOWERCASE_SERVICE:latest && docker stop ${LOWERCASE_SERVICE}_container || true && docker rm ${LOWERCASE_SERVICE}_container || true && docker run -d --name ${LOWERCASE_SERVICE}_container -p ${PORTS[$i]}:${PORTS[$i]} rahul4884/$LOWERCASE_SERVICE:latest"  # Use lowercase service name for container operations
            cd ..
          done
